//
// Created by Fir on 2024/4/15 015.
//

#pragma once
#ifndef ASTRA_CORE_SRC_ASTRA_UI_ITEM_PLUGIN_PLUGIN_H_
#define ASTRA_CORE_SRC_ASTRA_UI_ITEM_PLUGIN_PLUGIN_H_

#endif //ASTRA_CORE_SRC_ASTRA_UI_ITEM_PLUGIN_PLUGIN_H_
